version: '2.3'

services:

  # During development we want to build our Docker image from relevant
  # Dockerfiles, as opposed to pulling it from a repository somewhere.

  lab:
    build: 
      context: notebooks
      dockerfile: composer/Dockerfile

  docker_router:
    build: 
      context: notebooks/composer/docker_router
      dockerfile: Dockerfile

  llm_client:
    build:
      context: services/model
      dockerfile: llm_client.Dockerfile

  litellm_wrapper:
    build:
      context: services/model
      dockerfile: litellm_wrapper.Dockerfile
    env_file:
      - .env-dev

  chatbot:
    build: 
      context: notebooks/chatbot
      dockerfile: Dockerfile

  chatbot_rproxy:
    build: 
      context: notebooks/chatbot
      dockerfile: Dockerfile

  assessment:
    ports:
      - $DEV_ASSESSMENT_PORT:8080

  nginx:
    ports:
      - $DEV_NGINX_PORT:80
